# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: juannune <juannune@student.42madrid.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/12/13 02:02:24 by juannune          #+#    #+#              #
#    Updated: 2025/12/13 02:06:29 by juannune         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a
src = ft_print.c ft_putchar.c ft_puthex.c ft_putnbr.c ft_putstr.c ft_putunsing.c
CFLAGS = -Wall -Wextra -Werror
CC = cc
CFLAGS = 